name: PheWES
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.9
  - pip
  - pip:
      - numpy>=1.26.4
      - pandas>=2.2.3
      - polars>=1.0.0
      - scipy>=1.10.0
      - matplotlib>=3.7.0
      - seaborn>=0.12.0
      - jupyter>=1.0.0
      - notebook>=7.0.0
      - scikit-learn>=1.5.1
      - tqdm>=4.65.0
      - pytest>=7.3.0
      - black>=23.0.0
      - flake8>=6.0.0 
      - pyarrow>=19.0.0
      - shap>=0.48.0
      - snakemake>=9.8.0